// ERRCHECK: %compiler %enableEH %cmp_opt %f -o %output %diag_json
import stdx.effect.{Command, Resumption}

func foo(r: Resumption<Int64, Unit>) {
    resume r
}

main() {
    try {}
    handle (e: Command<Int64>, r: Resumption<Int64, Unit>) {
        foo(r)
    }
    0
}
// ASSERT: scan sema_resume_no_with


// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
